### ISSUE TITLE
The app produces fatal exception when trying to generate End Report

### ISSUE THREAD

**Issue by bondrtait** [VelbazhdSoftwareLLC/Broker-1961-for-Android#50]
**Pre-conditions:**
Start a New Game with two players

**Steps:**
1. Proceed to the end of the game (10th round, end game phase)
2. Tap the ellipsis button
3. Tap End Report

**Actual Result:**
The app redirects the user back to the main screen.
The fatal exception is produced:
`FATAL EXCEPTION: main
                                                                                                    Process: eu.veldsoft.broker, PID: 2537
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                                                                    	at eu.veldsoft.broker.model.Board.totalSale(Board.java:574)
                                                                                                    	at eu.veldsoft.broker.model.Board.endReport(Board.java:298)
                                                                                                    	at eu.veldsoft.broker.GameActivity.onOptionsItemSelected(GameActivity.java:306)`

**Expected result:**
The user should see the End Report.

**Comment by TodorBalabanov** [comment]
Thanks @bondrtait . We are working on this issue now. It is related to concurrent access to a container. Threading problem. We hope to find a solution soon.

**Comment by TodorBalabanov** [comment]
I think we have fixed it.
