### ISSUE TITLE
app crash in Android 11

### ISSUE THREAD

**Issue by leejie123** [VelbazhdSoftwareLLC/Broker-1961-for-Android#54]
java.lang.NullPointerException: Attempt to invoke virtual method 'int eu.veldsoft.broker.model.Player.money()' on a null object reference
	at eu.veldsoft.broker.model.Board.currentPlayerTradingPossibilities(Board.java:626)
	at eu.veldsoft.broker.GameActivity.onOptionsItemSelected(GameActivity.java:287)
	at android.app.Activity.onMenuItemSelected(Activity.java:4385)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1276)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:787)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:151)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:934)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:924)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1193)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3188)
	at android.widget.AbsListView$3.run(AbsListView.java:4106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8069)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by leejie123** [comment]
screenshots when app runs

![正在上传 y2{322530c} (b83bb25a-eb0a-4e32-a349-98a3f3bfc358 id=0x7f0a03c5 tag=BaseCommentFragment)…]()
![正在上传 y2{322530c} (b83bb25a-eb0a-4e32-a349-98a3f3bfc358 id=0x7f0a03c5 tag=BaseCommentFragment)…]()

**Comment by leejie123** [comment]
screenshots when app runs

![Screenshot_2024-03-23-02-30-15-504_eu.veldsoft.broker.jpg](https://github.com/VelbazhdSoftwareLLC/Broker-1961-for-Android/assets/15863698/d864588a-105b-4cd8-b4bc-00bd3c923058)

![Screenshot_2024-03-23-02-30-21-521_eu.veldsoft.broker.jpg](https://github.com/VelbazhdSoftwareLLC/Broker-1961-for-Android/assets/15863698/c347240a-cb84-436b-a530-23d4a9dde3ca)

**Comment by TodorBalabanov** [comment]
Thanks for the reported bug. I suppose you are using game version downloaded from F-Droid or Google Play. We have found these null pointer problems and they are fixed into development version of the source code.

**Comment by leejie123** [comment]
> Thanks for the reported bug. I suppose you are using game version downloaded from F-Droid or Google Play. We have found these null pointer problems and they are fixed into development version of the source code.

I have built the app, the problem resolved, thank you.
